# Generated by Django 6.0.4 on 2026-04-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_payment_schedule_booking_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'Buses'},
        ),
    ]
