# Generated by Django 6.0.4 on 2026-04-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_merchant_request_id_alter_booking_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
