# Generated by Django 6.0.4 on 2026-04-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_passenger_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
